apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../base
  - external-secret.yaml
  - httproute.yaml
images:
  - name: ghcr.io/square-kr/packet-plus-backend
    newTag: 35f2de856f2487488f8c077a9ed18c2182d97c38
