apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../base
  - external-secret.yaml
  - httproute.yaml
images:
  - name: ghcr.io/square-kr/packet-plus-backend
    newTag: 08afa7e0690a821eb35b57973b1fef8e181cfe45
