port: 3000
healthCheck:
  liveness: /health/live
  readiness: /health/ready
  timeoutSeconds: 2
image:
  name: ghcr.io/square-kr/packet-plus-backend
  version: 8aab0261
resources:
  cpu: "100m"
  memory: "256Mi"
secrets:
  - packet-plus-backend
imagePullSecrets:
  - ghcr-pull-secret
