apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: kube-system
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: doppler-infrastructure
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token
  data:
    - secretKey: api-token
      remoteRef:
        key: CLOUDFLARE_API_TOKEN
