apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: system
    app.kubernetes.io/component: gateway-controller
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: registry-1.docker.io/envoyproxy
    targetRevision: v1.8.3
    chart: gateway-helm
    helm:
      releaseName: envoy-gateway

  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
