apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: packet-plus-backend
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: projects
    app.kubernetes.io/component: packet-plus
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
    - list:
        elements:
          - env: dev
          - env: prod

  template:
    metadata:
      name: packet-plus-backend-{{.env}}
      labels:
        app.kubernetes.io/part-of: projects
        app.kubernetes.io/component: packet-plus
        app.kubernetes.io/instance: "{{.env}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default

      sources:
        - repoURL: https://github.com/Square-KR/kube
          targetRevision: HEAD
          ref: repo

        - repoURL: https://github.com/Square-KR/kube
          targetRevision: HEAD
          path: charts/app
          helm:
            releaseName: packet-plus-backend
            valueFiles:
              - $repo/projects/packet-plus-backend/{{.env}}/values.yaml

        - repoURL: https://github.com/Square-KR/kube
          targetRevision: HEAD
          path: projects/packet-plus-backend/{{.env}}

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.env}}"

      syncPolicy:
        managedNamespaceMetadata:
          labels:
            square-kr.io/ghcr-pull-secret: "true"
            pod-security.kubernetes.io/enforce: restricted
            pod-security.kubernetes.io/enforce-version: v1.33
            pod-security.kubernetes.io/audit: restricted
            pod-security.kubernetes.io/audit-version: v1.33
            pod-security.kubernetes.io/warn: restricted
            pod-security.kubernetes.io/warn-version: v1.33
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
