apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: datadog-postgresql-secret-reader
  namespace: datadog
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["datadog-secret"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: datadog-postgresql-secret-reader
  namespace: datadog
subjects:
  - kind: ServiceAccount
    name: datadog-agent
    namespace: datadog
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: datadog-postgresql-secret-reader
