apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: datadog-api-keys
  namespace: datadog
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: doppler-infrastructure
    kind: ClusterSecretStore
  target:
    name: datadog-api-keys
  data:
    - secretKey: api-key
      remoteRef:
        key: DATADOG_API_KEY
    - secretKey: app-key
      remoteRef:
        key: DATADOG_APP_KEY
