apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-ssm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-northeast-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-ssm-credentials
            namespace: kube-system
            key: AWS_ACCESS_KEY_ID
          secretAccessKeySecretRef:
            name: aws-ssm-credentials
            namespace: kube-system
            key: AWS_SECRET_ACCESS_KEY
