apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: doppler-infrastructure
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token-infrastructure
            namespace: kube-system
            key: token