apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notification-backend
  namespace: dev
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: doppler-dev
    kind: ClusterSecretStore
  target:
    name: notification-backend
  dataFrom:
    - find:
        name:
          regexp: "^NT_"
      rewrite:
        - regexp:
            source: "^NT_(.*)"
            target: "$1"
