port: 3000
healthCheck:
  liveness: /healthz
  readiness: /readyz
image:
  name: ghcr.io/square-kr/notification-backend
  version: "a416b2e4"
resources:
  cpu: "50m"
  memory: "256Mi"
secrets:
  - notification-backend
imagePullSecrets:
  - ghcr-pull-secret
