apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: better-auth
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: better-auth
  dataFrom:
    - find:
        name:
          regexp: "^/dev/better-auth/"
      rewrite:
        - regexp:
            source: "^/dev/better-auth/(.*)"
            target: "$1"
